branch-defaults:
  master:
    environment: env-dev
    group_suffix: null
  production:
    environment: prod-env
global:
  application_name: hello-cicd
  branch: null
  default_ec2_keyname: aws_hk
  default_platform: Node.js
  default_region: ap-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
