# JavaScript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:13.7.0

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: 
          name: Installing deployment dependencies
          working_directory: /
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install python-pip python-dev build-essential
            sudo pip install --upgrade setuptools
            sudo pip install awsebcli --upgrade

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test

      - run:
          name: Deploying
          command: eb deploy env-dev

workflows:
  version: 2
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - develop
                - master
                - production

# develop:
#   branch: /^(?!master$).*$/ #表示任何一個branch被觸發時都執行commands
#   commands:
#     - eb use env-dev --profile default #將eb切換到「env-dev」環境
#     - eb deploy --profile default #把程式deploy上「env-dev」
#     - echo 'hello in develop'
# production:
#   branch: master #当修改合进master时即会自动部署
#   commands:
#     - eb use env-prod --profile default 
#     - eb deploy --profile default
#     - echo 'hello in production'